### ISSUE TITLE
Unable to install from npm because of unpushed version

### ISSUE THREAD

**Issue by andrewnicols** [yui/yeti#61]
When trying to run yeti I'm getting an error.

The version specified in package.json is 0.2.25pre, which is not a tag in the repo (correctly) and not available in npm.

Output from update attempt below:

2014 nicols@tangerine:~> sudo npm update yeti -g
npm http GET https://registry.npmjs.org/yeti
npm http GET http://latest.yeti.cx/
npm http 304 https://registry.npmjs.org/yeti
npm http 200 http://latest.yeti.cx/
npm http GET https://registry.npmjs.org/yeti/0.2.25pre
npm http 404 https://registry.npmjs.org/yeti/0.2.25pre
npm ERR! Error: version not found: 0.2.25pre : yeti/0.2.25pre
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:269:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/index.js:142:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:856:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:808:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:883:14
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "update" "yeti" "-g"
npm ERR! cwd /Users/nicols
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nicols/npm-debug.log
npm ERR! not ok code 0

**Comment by reid** [comment]
When installing Yeti from latest.yeti.cx, you won't be able to use npm-update since the development snapshot does not exist on the registry.

Consider uninstalling Yeti and installing again with `npm install -g yeti`, which will install the latest version from the npm registry. You should then be able to run `npm update -g yeti`.

Alternatively, you can run `npm install -g http://latest.yeti.cx` if you'd like to remain on the development snapshot.

**Comment by reid** [comment]
Closing. If you feel this isn't resolved, please let me know.
