### ISSUE TITLE
DO I have to install Selenium Server?

### ISSUE THREAD

**Issue by rubelux** [yui/yeti#65]
FIrst off all, 
Congrats, You've done a great job here,

quick question, Do I have to have Selenium Server to lunch browser automatically?

I'm planning to integrate Yeti in a gruntjs task list, and I need to make it through terminal.

Thanks

Ruben

**Comment by evangoer** [comment]
Selenium Server is probably overkill for that. See this article about opening URLs from the command line in various operating systems: http://www.dwheeler.com/essays/open-files-urls.html. 

If you want your grunt task to wire up _multiple_ browsers to Yeti, most of the commands in that article open the file in only one browser, the default. (OS X is the exception -- its 'open' command has an option for choosing a different application.) But if you're not on OS X, you'll have to handle each browser individually. Fortunately, most browsers provide some kind of command line invocation. For example, here's how to invoke Firefox on various OSes: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options. Good luck!

**Comment by rubelux** [comment]
thank you!!,
