### ISSUE TITLE
Should coverage-dir be relative to basedir?

### ISSUE THREAD

**Issue by customcommander** [yui/yeti#80]
Hey Reid,

The new coverage options are a great addition to Yeti, thanks a lot for that!

I'm not sure whether the following is a bug or works as expected:

I've got the following repo structure:

```
/
    build/
    src/
        js/
        tests/
            unit/
                testrunner.html
    .yeti.json
```

And the following content in the `.yeti.json` file:

``` json
{
    "basedir": ".",
    "glob": "src/tests/**/testrunner*.html",
    "coverageOptions": {
        "instrument": false,
        "query": "filter=coverage",
        "coverage-report": "html",
        "coverage-dir": "cov"
    }
}
```

When I run:

``` shell
cd src/tests/unit
yeti -c testrunner.html
```

Would it make sense to have the `cov` directory created in `/cov` as opposed to `/src/tests/unit/cov` (as it currently is)?

Cheers,

**Comment by reid** [comment]
I agree! That's a bug. Thanks for reporting this :)
