### ISSUE TITLE
Future of YETI?

### ISSUE THREAD

**Issue by brunobasto** [yui/yeti#90]
It's more of a question than it is an issue. We're looking into using YETI as our test runner, but one thing that is holding us back is that we're not sure the project is going to be maintained since YUI have been discontinued. Can someone speak on that?

Thx,

**Comment by reid** [comment]
Thanks for asking. I am not planning to work on Yeti. I am open to adding maintainers to the project to accommodate feature development and bugfixes, so if you're interested in hacking on Yeti let me know.

**Comment by brunobasto** [comment]
Thank you for quick responding! I'll let you know if I can find someone wiling to help maintain the project.

Cheers

**Comment by okuryu** [comment]
Hey @reid, we don't have many TODOs for Yeti, but I'm game if you are. :smiley: 

BTW, I'm working for YUIDoc. It may be in a similar situation.
https://github.com/yui/yuidoc/releases
